// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ninja_Manager.Models;

#nullable disable

namespace Ninja_Manager.Migrations
{
    [DbContext(typeof(NinjaManagerDbContext))]
    [Migration("20241023170837_UpperCaseStats")]
    partial class UpperCaseStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GearNinja", b =>
                {
                    b.Property<int>("GearForNinjaId")
                        .HasColumnType("int");

                    b.Property<int>("NinjasForGearId")
                        .HasColumnType("int");

                    b.HasKey("GearForNinjaId", "NinjasForGearId");

                    b.HasIndex("NinjasForGearId");

                    b.ToTable("GearNinja");
                });

            modelBuilder.Entity("Ninja_Manager.Models.Gear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gears");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agility = 0,
                            Cost = 50,
                            Intelligence = 1,
                            Name = "Rusty Helm",
                            Strength = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Agility = 1,
                            Cost = 150,
                            Intelligence = 2,
                            Name = "Iron Helm",
                            Strength = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Agility = 0,
                            Cost = 300,
                            Intelligence = 5,
                            Name = "Crown of Wisdom",
                            Strength = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Agility = 1,
                            Cost = 60,
                            Intelligence = 1,
                            Name = "Leather Armor",
                            Strength = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Agility = 1,
                            Cost = 180,
                            Intelligence = 2,
                            Name = "Iron Chestplate",
                            Strength = 4,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Agility = 2,
                            Cost = 350,
                            Intelligence = 3,
                            Name = "Dragonscale Chest",
                            Strength = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Agility = 1,
                            Cost = 40,
                            Intelligence = 1,
                            Name = "Cloth Gloves",
                            Strength = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            Agility = 2,
                            Cost = 100,
                            Intelligence = 2,
                            Name = "Leather Gloves",
                            Strength = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            Agility = 1,
                            Cost = 250,
                            Intelligence = 1,
                            Name = "Gauntlets of Power",
                            Strength = 5,
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            Agility = 2,
                            Cost = 50,
                            Intelligence = 0,
                            Name = "Worn Boots",
                            Strength = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 11,
                            Agility = 2,
                            Cost = 130,
                            Intelligence = 1,
                            Name = "Iron Boots",
                            Strength = 3,
                            Type = 3
                        },
                        new
                        {
                            Id = 12,
                            Agility = 6,
                            Cost = 280,
                            Intelligence = 0,
                            Name = "Boots of Swiftness",
                            Strength = 2,
                            Type = 3
                        },
                        new
                        {
                            Id = 13,
                            Agility = 1,
                            Cost = 30,
                            Intelligence = 1,
                            Name = "Copper Ring",
                            Strength = 1,
                            Type = 4
                        },
                        new
                        {
                            Id = 14,
                            Agility = 2,
                            Cost = 120,
                            Intelligence = 2,
                            Name = "Silver Ring",
                            Strength = 1,
                            Type = 4
                        },
                        new
                        {
                            Id = 15,
                            Agility = 4,
                            Cost = 270,
                            Intelligence = 4,
                            Name = "Ring of the Ancients",
                            Strength = 0,
                            Type = 4
                        },
                        new
                        {
                            Id = 16,
                            Agility = 1,
                            Cost = 40,
                            Intelligence = 1,
                            Name = "Wooden Necklace",
                            Strength = 0,
                            Type = 5
                        },
                        new
                        {
                            Id = 17,
                            Agility = 2,
                            Cost = 140,
                            Intelligence = 3,
                            Name = "Silver Pendant",
                            Strength = 1,
                            Type = 5
                        },
                        new
                        {
                            Id = 18,
                            Agility = 3,
                            Cost = 320,
                            Intelligence = 5,
                            Name = "Amulet of the Phoenix",
                            Strength = 0,
                            Type = 5
                        });
                });

            modelBuilder.Entity("Ninja_Manager.Models.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");
                });

            modelBuilder.Entity("GearNinja", b =>
                {
                    b.HasOne("Ninja_Manager.Models.Gear", null)
                        .WithMany()
                        .HasForeignKey("GearForNinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ninja_Manager.Models.Ninja", null)
                        .WithMany()
                        .HasForeignKey("NinjasForGearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
