// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ninja_Manager.Models;

#nullable disable

namespace Ninja_Manager.Migrations
{
    [DbContext(typeof(NinjaManagerDbContext))]
    partial class NinjaManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GearNinja", b =>
                {
                    b.Property<int>("GearForNinjaId")
                        .HasColumnType("int");

                    b.Property<int>("NinjasForGearId")
                        .HasColumnType("int");

                    b.HasKey("GearForNinjaId", "NinjasForGearId");

                    b.HasIndex("NinjasForGearId");

                    b.ToTable("GearNinja");
                });

            modelBuilder.Entity("Ninja_Manager.Models.Gear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("agility")
                        .HasColumnType("int");

                    b.Property<int>("intelligence")
                        .HasColumnType("int");

                    b.Property<int>("strength")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gears");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 50,
                            Name = "Rusty Helm",
                            agility = 0,
                            intelligence = 1,
                            strength = 1,
                            type = 0
                        },
                        new
                        {
                            Id = 2,
                            Cost = 150,
                            Name = "Iron Helm",
                            agility = 1,
                            intelligence = 2,
                            strength = 3,
                            type = 0
                        },
                        new
                        {
                            Id = 3,
                            Cost = 300,
                            Name = "Crown of Wisdom",
                            agility = 0,
                            intelligence = 5,
                            strength = 2,
                            type = 0
                        },
                        new
                        {
                            Id = 4,
                            Cost = 60,
                            Name = "Leather Armor",
                            agility = 1,
                            intelligence = 1,
                            strength = 2,
                            type = 1
                        },
                        new
                        {
                            Id = 5,
                            Cost = 180,
                            Name = "Iron Chestplate",
                            agility = 1,
                            intelligence = 2,
                            strength = 4,
                            type = 1
                        },
                        new
                        {
                            Id = 6,
                            Cost = 350,
                            Name = "Dragonscale Chest",
                            agility = 2,
                            intelligence = 3,
                            strength = 6,
                            type = 1
                        },
                        new
                        {
                            Id = 7,
                            Cost = 40,
                            Name = "Cloth Gloves",
                            agility = 1,
                            intelligence = 1,
                            strength = 1,
                            type = 2
                        },
                        new
                        {
                            Id = 8,
                            Cost = 100,
                            Name = "Leather Gloves",
                            agility = 2,
                            intelligence = 2,
                            strength = 2,
                            type = 2
                        },
                        new
                        {
                            Id = 9,
                            Cost = 250,
                            Name = "Gauntlets of Power",
                            agility = 1,
                            intelligence = 1,
                            strength = 5,
                            type = 2
                        },
                        new
                        {
                            Id = 10,
                            Cost = 50,
                            Name = "Worn Boots",
                            agility = 2,
                            intelligence = 0,
                            strength = 1,
                            type = 3
                        },
                        new
                        {
                            Id = 11,
                            Cost = 130,
                            Name = "Iron Boots",
                            agility = 2,
                            intelligence = 1,
                            strength = 3,
                            type = 3
                        },
                        new
                        {
                            Id = 12,
                            Cost = 280,
                            Name = "Boots of Swiftness",
                            agility = 6,
                            intelligence = 0,
                            strength = 2,
                            type = 3
                        },
                        new
                        {
                            Id = 13,
                            Cost = 30,
                            Name = "Copper Ring",
                            agility = 1,
                            intelligence = 1,
                            strength = 1,
                            type = 4
                        },
                        new
                        {
                            Id = 14,
                            Cost = 120,
                            Name = "Silver Ring",
                            agility = 2,
                            intelligence = 2,
                            strength = 1,
                            type = 4
                        },
                        new
                        {
                            Id = 15,
                            Cost = 270,
                            Name = "Ring of the Ancients",
                            agility = 4,
                            intelligence = 4,
                            strength = 0,
                            type = 4
                        },
                        new
                        {
                            Id = 16,
                            Cost = 40,
                            Name = "Wooden Necklace",
                            agility = 1,
                            intelligence = 1,
                            strength = 0,
                            type = 5
                        },
                        new
                        {
                            Id = 17,
                            Cost = 140,
                            Name = "Silver Pendant",
                            agility = 2,
                            intelligence = 3,
                            strength = 1,
                            type = 5
                        },
                        new
                        {
                            Id = 18,
                            Cost = 320,
                            Name = "Amulet of the Phoenix",
                            agility = 3,
                            intelligence = 5,
                            strength = 0,
                            type = 5
                        });
                });

            modelBuilder.Entity("Ninja_Manager.Models.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");
                });

            modelBuilder.Entity("GearNinja", b =>
                {
                    b.HasOne("Ninja_Manager.Models.Gear", null)
                        .WithMany()
                        .HasForeignKey("GearForNinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ninja_Manager.Models.Ninja", null)
                        .WithMany()
                        .HasForeignKey("NinjasForGearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
